[project]
name = "learn-github"
version = "0.1.0"
description = ""
authors = [
    {name = "Tyler",email = "tylerjas1230@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy (>=2.4.1,<3.0.0)"
]

[tool.poetry]
packages = [{include = "learn_github", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
